config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  resources :projects
  resources :tickets
  resources :bugs, controller: 'tickets'
  resources :features, controller: 'tickets'
  resource :project_enrollment
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bug.rb
# frozen_string_literal: true

class Bug < Ticket
  enum status: { New: 'New', Started: 'Started', Resolved: 'Resolved' }
end

app/models/developer.rb
# frozen_string_literal: true

class Developer < User
  has_many :tickets,              foreign_key: 'assigned_to_id', inverse_of: :developer, dependent: :nullify
  has_many :project_enrollments,  dependent: :destroy
  has_many :projects,             through: :project_enrollments
end

app/models/feature.rb
# frozen_string_literal: true

class Feature < Ticket
  enum status: { New: 'New', Started: 'Started', Completed: 'Completed' }
end

app/models/manager.rb
# frozen_string_literal: true

class Manager < User
  has_many :projects, dependent: :destroy
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  has_many :tickets,              dependent: :destroy
  has_many :project_enrollments,  dependent: :destroy
  has_many :developers,           through: :project_enrollments, class_name: 'User'

  belongs_to :manager,            class_name: 'User'

  validates :title, :description, presence: true
end

app/models/project_enrollment.rb
# frozen_string_literal: true

class ProjectEnrollment < ApplicationRecord
  belongs_to :developer, class_name: 'User'
  belongs_to :project

  validates :developer, uniqueness: { scope: :project }
end

app/models/project_management.rb
class ProjectManagement < ApplicationRecord
  belongs_to :Manager
  belongs_to :project
end

app/models/qa.rb
# frozen_string_literal: true

class QA < User
  has_many :tickets, foreign_key: 'creator_id', dependent: :nullify
end

app/models/ticket.rb
# frozen_string_literal: true

class Ticket < ApplicationRecord
  enum type: { Bug: 'Bug', Feature: 'Feature' }

  belongs_to :developer,  class_name: 'User', foreign_key: 'assigned_to_id', inverse_of: :tickets, optional: true
  belongs_to :qa,         class_name: 'User', foreign_key: 'creator_id'
  belongs_to :project

  has_one_attached :screen_shot

  validates :title, :type, :status, presence: true
  validates :title, uniqueness: { scope: :project }

  def screen_shot_thumbnail
    screen_shot
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum type: { Developer: 'Developer', Manager: 'Manager', QA: 'QA' }

  validates :name, :email, :type, presence: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit::Authorization

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  rescue_from ActiveRecord::RecordNotUnique, with: :record_not_unique
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name type])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name type])
  end

  def record_not_found
    redirect_to root_path
    flash[:notice] = 'Record not Found!'
  end

  def record_not_unique
    redirect_to root_path
    flash[:notice] = 'Record not unique!'
  end

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    redirect_to(request.referer || root_path)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index; end
end

app/controllers/project_enrollments_controller.rb
# frozen_string_literal: true

class ProjectEnrollmentsController < ApplicationController
  def create; end

  def destroy; end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy]

  def index
    @projects = policy_scope(Project)
  end

  def show; end

  def new
    @project = Project.new
    authorize @project
  end

  def edit; end

  def create
    @project = current_user.projects.build(project_params)
    authorize @project

    if @project.save
      set_project_enrollment
      flash[:notice] = 'Project was successfully created.'
      render :show
    else
      flash[:alert] = 'Project was not created.'
      render :new
    end
  end

  def update
    if @project.update(project_params)
      set_project_enrollment
      flash[:notice] = 'Project was successfully updated.'
      render :show
    else
      flash[:alert] = 'Project was not updated.'
      render :edit
    end
  end

  def destroy
    if @project.destroy
      flash[:notice] = 'Project was successfully destroyed.'
      render :index
    else
      flash[:alert] = 'Project was not destroyed.'
      render :show
    end
  end

  private

  def set_project
    @project = Project.find(params[:id])
    authorize @project
  end

  def project_params
    params.require(:project).permit(:title, :description)
  end

  def project_enrollment_params
    params.require(:project).permit(:developer_id)
  end

  def set_project_enrollment
    @project.project_enrollments.create(project_enrollment_params)
  end
end

app/controllers/tickets_controller.rb
# frozen_string_literal: true

class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[show edit update destroy]

  def index
    @tickets = policy_scope(Ticket)
    authorize @tickets, policy_class: TicketPolicy
  end

  def show; end

  def new
    @ticket = Ticket.new
    authorize @ticket, policy_class: TicketPolicy
  end

  def edit; end

  def create
    @ticket = current_user.tickets.build(ticket_params)
    authorize @ticket, policy_class: TicketPolicy

    if @ticket.save
      flash[:notice] = 'Ticket was successfully created.'
      render :show
    else
      flash[:alert] = 'Ticket was not created.'
      render :new
    end
  end

  def update
    if @ticket.update(edit_ticket_params)
      flash[:notice] = 'Ticket was successfully updated.'
      render :show
    else
      flash[:alert] = 'Ticket was not updated.'
      render :edit
    end
  end

  def destroy
    if @ticket.destroy
      flash[:notice] = 'Ticket was successfully destroyed.'
      render :index
    else
      flash[:alert] = 'Ticket was not destroyed.'
      render :show
    end
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
    authorize @ticket, policy_class: TicketPolicy
  end

  def ticket_params
    params.require(:ticket).permit(:title, :type, :status, :project_id, :description, :deadline, :screen_shot, :assigned_to_id)
  end

  def edit_ticket_params
    if @ticket.Bug?
      params.require(:bug).permit(:title, :type, :status, :project_id, :description, :deadline, :screen_shot, :assigned_to_id)
    else
      params.require(:feature).permit(:title, :type, :status, :project_id, :description, :deadline, :screen_shot, :assigned_to_id)
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Bugzilla', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
          </li>
          <% if current_user.Manager? %>
            <li class="nav-item">
              <%= link_to 'New Project', new_project_path, class:"nav-link" %>
            </li>
          <% end %>
          <% if current_user.QA? %>
            <li class="nav-item">
              <%= link_to 'New Ticket', new_ticket_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Tickets', tickets_path, class:"nav-link" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to 'Projects', projects_path, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<% if user_signed_in? %>
  <div class="main-body">
    <div class="row gutters-sm">
      <div class="col-md-4 mb-3">
        <div class="card">
          <div class="card-body">
            <div class="d-flex flex-column align-items-center text-center">
              <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle" width="150">
              <div class="mt-3">
                <h4><%= current_user.name %></h4>
                <p class="text-secondary mb-1"><%= current_user.type %></p>
                <p class="text-muted font-size-sm">Bay Area, San Francisco, CA</p>
                <button class="btn btn-primary">Follow</button>
                <button class="btn btn-outline-primary">Message</button>
              </div>
            </div>
          </div>
        </div>
        <div class="card mt-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
              <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-globe mr-2 icon-inline"><circle cx="12" cy="12" r="10"></circle><line x1="2" y1="12" x2="22" y2="12"></line><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path></svg>Website</h6>
              <span class="text-secondary">https://bootdey.com</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
              <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github mr-2 icon-inline"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>Github</h6>
              <span class="text-secondary">bootdey</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
              <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-twitter mr-2 icon-inline text-info"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg>Twitter</h6>
              <span class="text-secondary">@bootdey</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
              <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-instagram mr-2 icon-inline text-danger"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line></svg>Instagram</h6>
              <span class="text-secondary">bootdey</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
              <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-facebook mr-2 icon-inline text-primary"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path></svg>Facebook</h6>
              <span class="text-secondary">bootdey</span>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-8">
        <div class="card mb-3">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Full Name</h6>
              </div>
              <div class="col-sm-9 text-secondary">
                <%= current_user.name %>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Email</h6>
              </div>
              <div class="col-sm-9 text-secondary">
                <%= current_user.email %>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Phone</h6>
              </div>
              <div class="col-sm-9 text-secondary">
                (239) 816-9029
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Mobile</h6>
              </div>
              <div class="col-sm-9 text-secondary">
                (320) 380-4539
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Address</h6>
              </div>
              <div class="col-sm-9 text-secondary">
                Bay Area, San Francisco, CA
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-12">
                <%= link_to 'Edit', edit_user_registration_path, class:"btn btn-info" %>
              </div>
            </div>
          </div>
        </div>

        <div class="row gutters-sm">
          <div class="col-sm-6 mb-3">
            <div class="card h-100">
              <div class="card-body">
                <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">assignment</i>Project Status</h6>
                <small>Web Design</small>
                <div class="progress mb-3" style="height: 5px">
                  <div class="progress-bar bg-primary" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <small>Website Markup</small>
                <div class="progress mb-3" style="height: 5px">
                  <div class="progress-bar bg-primary" role="progressbar" style="width: 72%" aria-valuenow="72" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <small>One Page</small>
                <div class="progress mb-3" style="height: 5px">
                  <div class="progress-bar bg-primary" role="progressbar" style="width: 89%" aria-valuenow="89" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <small>Mobile Template</small>
                <div class="progress mb-3" style="height: 5px">
                  <div class="progress-bar bg-primary" role="progressbar" style="width: 55%" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <small>Backend API</small>
                <div class="progress mb-3" style="height: 5px">
                  <div class="progress-bar bg-primary" role="progressbar" style="width: 66%" aria-valuenow="66" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-sm-6 mb-3">
            <div class="card h-100">
              <div class="card-body">
                <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">assignment</i>Project Status</h6>
                <small>Web Design</small>
                <div class="progress mb-3" style="height: 5px">
                  <div class="progress-bar bg-primary" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <small>Website Markup</small>
                <div class="progress mb-3" style="height: 5px">
                  <div class="progress-bar bg-primary" role="progressbar" style="width: 72%" aria-valuenow="72" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <small>One Page</small>
                <div class="progress mb-3" style="height: 5px">
                  <div class="progress-bar bg-primary" role="progressbar" style="width: 89%" aria-valuenow="89" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <small>Mobile Template</small>
                <div class="progress mb-3" style="height: 5px">
                  <div class="progress-bar bg-primary" role="progressbar" style="width: 55%" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <small>Backend API</small>
                <div class="progress mb-3" style="height: 5px">
                  <div class="progress-bar bg-primary" role="progressbar" style="width: 66%" aria-valuenow="66" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% else %>
  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bugzilla</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'home/navbar' %>
    <div class="container">
      <br>
      <% if notice %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <%= notice %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <%= alert %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
  </body>
</html>

app/views/projects/_form.html.erb
<div class="card-body">
  <%= form_with(model: project, local: true) do |form| %>
    <% if project.errors.any? %>
      <div id="error_explanation" class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <strong>
          <%= I18n.t("errors.messages.not_saved",
                    count: project.errors.count,
                    resource: project.class.model_name.human.downcase)
          %>
        </strong>
        <% project.errors.full_messages.each do |message| %>
          <div>
            <%= message %>
          </div>
        <% end %>
      </div>
    <% end %>
    <%= form.text_field :title, autocomplete: "title", class: "form-control", placeholder: "Title" %>
    <br>
    <%= form.text_field :description, autocomplete: "description", class: "form-control", placeholder: "Description" %>
    <br>
    <%= form.label :developer %>
    <br>
    <%= form.select :developer_id, Developer.all.map { |d| [d.name, d.id] }, include_blank: true %>
    <br><br>
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/projects/edit.html.erb
<div class="card">
  <div class="card-header">
    <h1>Editing Project</h1>
  </div>
  <%= render 'form', project: @project %>
</div>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class="card">
  <div class="card-header">
    <h1>Projects</h1>
  </div>
  <div class="card-body">
    <% @projects.each do |project| %>
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= project.title %></h5>
          <p class="card-text"><%= project.description %></p>
          <%= link_to 'Show', project, class: 'btn btn-info' %>
            <% if current_user.Manager? %>
             | <%= link_to 'Edit', edit_project_path(project), class: 'btn btn-primary' %> | 
              <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
          <% end %>
        </div>
      </div>
      <br>
    <% end %>
  </div>
</div>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<div class="card">
  <div class="card-header">
    <h1>New Project</h1>
  </div>
  <%= render 'form', project: @project %>
</div>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div class="card mb-3">
  <div class="card-header">
    <h1>Project Title: <i><%= @project.title %></i></h1>
  </div>
  <div class="card-body">
    <p class="card-text"><strong>Description: </strong><%= @project.description %></p>
    <p class="card-text"><strong>Project Manager: </strong><%= User.find(@project.manager_id).name %></p>
    <p class="card-text"><strong>Assigned Developers: </strong></p>
    <ul>
      <% @project.developers.each do |d| %>
        <li>
          <p class="card-text"><strong>Developer Name: </strong><%= d.name %></p>
        </li>
      <% end %>
    </ul>
    <p class="card-text"><strong>Active Tickets: </strong></p>
    <% @project.tickets.each do |ticket| %>
      <div class="card">
        <div class="card-body">
          <p class="card-text"><strong>Ticket Title: </strong><%= ticket.title %></p>
          <p class="card-text"><strong>Ticket Description: </strong><%= ticket.description %></p>
          <p class="card-text"><strong>Ticket Type: </strong><%= ticket.type %></p>
          <p class="card-text"><strong>Ticket Status: </strong><%= ticket.status %></p>
          <% if current_user.Developer? || current_user.QA? %>
            <%= link_to 'Show', ticket, class: 'btn btn-primary mb-3' %>
          <% end %>
          <% if current_user.Developer? %>
            <%= form_for ticket do |f| %>
              <%= f.hidden_field :assigned_to_id, :value => current_user.id %>
              <%= f.submit 'Assign Ticket to Yourself', class: 'btn btn-success' %>
            <% end %>
          <% end %>
        </div>
      </div>
      <br>
    <% end %>
    <%= link_to 'Edit', edit_project_path(@project), class: 'btn btn-warning' %> |
    <%= link_to 'Back', projects_path, class: 'btn btn-info' %>
  </div>
</div>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %>

app/views/tickets/index.html.erb
<div class="card">
  <div class="card-header">
    <h1>Tickets</h1>
  </div>
  <div class="card-body">
    <% @tickets.each do |ticket| %>
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><strong>Ticket Title: </strong><%= ticket.title %></h5>
          <p class="card-text"><strong>Ticket Type: </strong><%= ticket.type %></p>
          <p class="card-text"><strong>Ticket Status: </strong><%= ticket.status %></p>
          <p class="card-text"><strong>Ticket Description: : </strong><%= ticket.description %></p>
          <p class="card-text"><small class="text-muted">Deadline: <%= ticket.deadline %></small></p>
          <%= link_to 'Show', ticket, class: 'btn btn-info' %> | 
          <%= link_to 'Edit', edit_ticket_path(ticket), class: 'btn btn-primary' %> | 
          <%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </div>
      </div>
      <br>
    <% end %>
  </div>
</div>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<div class="card mb-3">
  <% if @ticket.screen_shot.attached? %>
    <%= image_tag(@ticket.screen_shot_thumbnail, class: 'card-img-top') %>
  <% end %>
  <div class="card-body">
    <h5 class="card-title"><strong>Ticket Title: </strong><%= @ticket.title %></h5>
    <p class="card-text"><strong>Ticket Type: </strong><%= @ticket.type %></p>
    <p class="card-text"><strong>Ticket Status: </strong><%= @ticket.status %></p>
    <p class="card-text"><strong>Ticket Description: </strong><%= @ticket.description %></p>
    <p class="card-text"><small class="text-muted">Deadline: <%= @ticket.deadline %></small></p>
    <%= form_for @ticket do |f| %>
      <% if @ticket.Bug? %>
        <%= f.label :status %>
        <%= f.select :status, Bug.statuses.keys, include_blank: true %>
      <% else %>
        <%= f.label :status %>
        <%= f.select :status, Feature.statuses.keys, include_blank: true %>
      <% end %>
      <%= f.submit 'Set Status', class: 'btn btn-success' %>
    <% end %>
    <%= link_to 'Edit', edit_ticket_path(@ticket), class: 'btn btn-warning' %>
  </div>
</div>